---

- hosts: all

  vars:
    rdmo_url: "{{ inventory_hostname }}"
    rdmo_user: "{{ rdmo_instance }}"
    rdmo_group: "{{ rdmo_instance }}"
    rdmo_home: "/srv/{{ rdmo_instance }}"
    rdmo_db: "rdmo_{{ rdmo_instance }}"
    rdmo_service: "{{ rdmo_instance }}"

  tasks:

  - name: Install prerequisites
    apt:
      name:
      - build-essential
      - libxml2-dev
      - libxslt-dev
      - zlib1g-dev
      - python3-dev
      - python3-pip
      - python3-venv
      - python3-psycopg2
      - git
      - pandoc
      - texlive
      - texlive-xetex
      - lmodern
      - librsvg2-bin
      - postgresql
      - libpq-dev
      - python3-psycopg2
      - nginx
      - certbot
      - python3-certbot-nginx
      update_cache: true
    tags:
    - prerequisites

  - name: Create rdmo user
    user:
      name: "{{ rdmo_user }}"
      group: "{{ rdmo_group }}"
      password: "*"
      home: "{{ rdmo_home }}"
      shell: /bin/bash

  - name: Create rdmo postgres user
    become: true
    become_user: postgres
    postgresql_user:
      name: "{{ rdmo_user }}"
      role_attr_flags: CREATEDB,NOSUPERUSER

  - name: Create rdmo postgres database
    become: true
    become_user: postgres
    postgresql_db:
      name: "{{ rdmo_db }}"

  - name: Clone the rdmo-app repository
    become: true
    become_user: "{{ rdmo_user }}"
    git:
      repo: "{{ rdmo_repository }}"
      dest: "{{ rdmo_home }}/rdmo-app"
      accept_hostkey: yes

  - name: Copy config/settings/local.py
    become: true
    become_user: "{{ rdmo_user }}"
    template:
      src: "local.py.j2"
      dest: "{{ rdmo_home }}/rdmo-app/config/settings/local.py"
      force: false
    vars:
      rdmo_secret_key: "{{ lookup('community.general.random_string', length=64) }}"
    when: "lookup('ansible.builtin.fileglob', 'templates/local.py.j2') != []"

  - name: Copy fixtures
    become: true
    become_user: "{{ rdmo_user }}"
    template:
      src: "fixtures.json.j2"
      dest: "{{ rdmo_home }}/rdmo-app/fixtures.json"
      force: false
    when: "lookup('ansible.builtin.fileglob', 'templates/fixtures.json.j2') != []"

  - name: Create Systemd service file
    template:
      src: templates/rdmo.service.j2
      dest: /etc/systemd/system/{{ rdmo_service }}.service

  - name: Obtain certificate for {{ rdmo_url }}
    command:
      cmd: |
        certbot certonly --standalone -d {{ rdmo_url }}
        --non-interactive --agree-tos --email {{ certbot_email }}
      creates: /etc/letsencrypt/live/{{ rdmo_url }}/cert.pem

  - name: Create NGINX config file
    template:
      src: templates/rdmo.conf.j2
      dest: /etc/nginx/sites-available/{{ rdmo_url }}.conf

  - name: Enable NGINX config file
    file:
      src: /etc/nginx/sites-available/{{ rdmo_url }}.conf
      dest: /etc/nginx/sites-enabled/{{ rdmo_url }}.conf
      state: link
